### ISSUE TITLE
Disable publication checkboxes when metadata invalid

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/core-geonetwork#13]
When the "Allow publication of invalid metadata" option is disabled, the privileges checkboxes in the privilege dialog can be selected; of course if the metadata is invalid it will not be published.

It would be useful to disable the publication checkboxes if the metadata is invalid or if it has never been validated.

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
Here the pull request https://github.com/geosolutions-it/core-geonetwork/pull/17

**Comment by etj** [comment]
Related issue in official repo:
   https://github.com/geonetwork/core-geonetwork/issues/3677
