### ISSUE TITLE
Massive validation not properly working

### ISSUE THREAD

**Issue by taba90** [geosolutions-it/core-geonetwork#15]
La validazione massiva non sembra funzionare correttamente perché se il metadato singolo passa la validazione poi validandolo di nuovo dall'elenco non la passa più e torna ad essere in stato non valido. 

---

Massive validation seems to not properly working.
If a single metadata pass the validation, trying to validating it again from the list make it turns out to be invalid and is being put back in an invalid status.

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
issue reproduced

**Comment by taba90** [comment]
pull request https://github.com/geosolutions-it/core-geonetwork/pull/20

**Comment by etj** [comment]
@taba90 I see that the PR handles errors when the schemalocations points to URL that are not managed by the oasis schema file.  Probably this is not the behavior of the validator used in the editor.
We should have ideally the same code path for the validation, both for editor and the massive validation; if not possibile, we should handle the schemas and the errors in the very same way in order to have the same result in the two validation cases.

**Comment by tdipisa** [comment]
Considering the updates we did on the RNDT plugin, the provided PR doesn't properly fits the real use case it seems. We provided a lot of enhancements on the RNDT plugin, therefore we should ask the client to try to reproduce the issue. As @etj required, we should have a more concrete metadata sample to check it and see if the validation problem can be reproduced now.

**Comment by tdipisa** [comment]
La precedente PR fatta da @taba90 https://github.com/geosolutions-it/core-geonetwork/pull/28 non risulta correggere il problema in modo appropriato.

**Comment by etj** [comment]
Il lavoro sul plugin RNDT è terminato ed è stato ora possibile replicare l'errore: metadati che validano correttamente nell'editor non vengono validati nella validazione batch.
Questo è un errore relativo a core-geonetwork.
Come riportato in un commento precedente, il fix migliore sarebbe fare in modo che validazione singola e massiva usino lo stesso codice, ma questa è una modifica strutturale eccessiva. Ci basta un fix che renda coerente l'esito della validazione nei due casi.
