### ISSUE TITLE
Setup CD with Jenkins

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#18]
A Jenkins job needs to be configured for the GN RNDT instance to be used for testing and demo purposes.

**Comment by randomorder** [comment]
What's the machine to work on?

**Comment by tdipisa** [comment]
@randomorder issue #19 has been created for this. Let's wait for @etj to confirm the system requirements.

**Comment by tdipisa** [comment]
@randomorder, @etj confirmed the GN installation in the VM has been completed. I moved this issue in ready.

**Comment by simboss** [comment]
I have removed @etj from the responsible parties.

[Here](https://docs.google.com/document/d/1iYwASs_MbuLAmhsfEvuuh1yp0Q9NUZD3h0vM8Cdy8WI/edit#) is some documentation provided by him on the set up.

**Comment by randomorder** [comment]
updates @giacomoc92 ?

**Comment by conjame** [comment]
A job has been made for [building the plugin](https://build.geo-solutions.it/jenkins/view/GeoNetwork/job/Build%20GeoNetwork%20rndt%20iso19139/) from https://github.com/geosolutions-it/iso19139.rndt

A second one for [building geonetwork](https://build.geo-solutions.it/jenkins/job/Build%20GeoNetwork-RNDT-3.10.x-rndt3/) from https://github.com/geosolutions-it/core-geonetwork with the plugin from the previous job

both of them looking for changes in the respective repositeries every five minutes

And a final one for deploying
https://build.geo-solutions.it/jenkins/view/GeoNetwork/job/Deploy%20GeoNetwork-RNDT-3.10.x-rndt3/

build running at http://gn3-rndt.geo-solutions.it/geonetwork

**Comment by randomorder** [comment]
Is it working? Are you done?

**Comment by conjame** [comment]
yes, everything seems to be working properly

**Comment by randomorder** [comment]
@etj ?

**Comment by conjame** [comment]
As Emanuele noted, we need to update the data directory to include the same changes done to the GN war. 

I am going to update the jobs in order to update the datadir with the content of WEB-INF/data/config/schema_plugins/

**Comment by conjame** [comment]
I have updated the [build job](https://build.geo-solutions.it/jenkins/view/GeoNetwork/job/Build_GeoNetwork-RNDT-3.10.x-rndt3/) to make a copy of WEB-INF/data/config/schema_plugins/ and the [deploy job](https://build.geo-solutions.it/jenkins/view/GeoNetwork/job/Deploy%20GeoNetwork-RNDT-3.10.x-rndt3/) to unpack it to the datadir
