### ISSUE TITLE
Create VM for GN demo

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#19]
A VM need to be created and configured for CD of GN instance (issue #18), minimum system requirements are (TBC):

CPU: 4 core
RAM: 8 GB
HD: 30 GB
OS: CentOS 7

**Comment by tdipisa** [comment]
@etj can you please confirm the system requirements specified in the description are enough?

**Comment by etj** [comment]
Shall we upgrade our default platform to CentOS8?

**Comment by randomorder** [comment]
> Shall we upgrade our default platform to CentOS8?

Question for me or @tdipisa ? What's in the client environment? Can we use Docker @tdipisa ?

**Comment by tdipisa** [comment]
@randomorder 

> Question for me or @tdipisa ? What's in the client environment? 

We don't know this, I think it is not so relevant for the moment, GN should be able to nativelly work in different environments including Docker. Probably the client is not using Docker, but if having that deployment solution for our DEV server is easier, we can use it.
@etj what do you think?

**Comment by randomorder** [comment]
@etj please open an issue with the provided template on the DevOps repo
https://github.com/geosolutions-it/DevOps/issues/new/choose

**Comment by randomorder** [comment]
moving to blocked

**Comment by tdipisa** [comment]
@randomorder the issue has been created here:
https://github.com/geosolutions-it/DevOps/issues/271

**Comment by conjame** [comment]
I believe this issue has been superseded by https://github.com/geosolutions-it/DevOps/issues/271. Can we close this?

**Comment by randomorder** [comment]
yes

**Comment by tdipisa** [comment]
I need this here to keep track of the activities in one single kanban, you can work on geosolutions-it/DevOps#271 but I need this one.
