### ISSUE TITLE
Validazione massiva - messaggio

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#22]
La validazione presenta problemi legati al plugin RNDT che sono stati descritti nella sezione specifica.
Inoltre il messaggio che visualizza alla fine della validazione è errato, sembra non carichi correttamente qualche oggetto. Il servizio di validazione è lanciabile anche dalla pagina di ricerca (previo login) ma non caricando correttamente il messaggio finale non ci sono indicazioni sul risultato della validazione.

**Comment by taba90** [comment]
working on this

**Comment by taba90** [comment]
internal pull request https://github.com/geosolutions-it/core-geonetwork/pull/24

**Comment by tdipisa** [comment]
@etj please check if the PR connected to the issue can be merged or not.

**Comment by etj** [comment]
Il problema non è relativo al plugin ma a geonetwork core.
Creata issue https://github.com/geonetwork/core-geonetwork/issues/5322
