### ISSUE TITLE
Validatore INSPIRE esterno

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#39]
Impostazione validatore esterno (config locale)

**Comment by taba90** [comment]
Configurazione validatore esterno. Alcune recenti modifiche a gn rendono necessario un xsl di conversione a iso19139 per utilizzare il validator INSPIRE esterno, oltre che all'impostazione dell'url del validator da schermata admin delle impostazioni

**Comment by taba90** [comment]
depends on https://github.com/geosolutions-it/iso19139.rndt/issues/142

**Comment by tdipisa** [comment]
closed in favor of https://github.com/geosolutions-it/iso19139.rndt/issues/142
@taba90 please remember to update the documentation to report what is needed for the client installation
