### ISSUE TITLE
Multipli CSW virtual endpoint

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#45]
Ogni pubblica amministrazione deve avere un endpoint virtuale CSW dedicato. Impostazione degli endpoint CSW per i gruppi configurati.

**Comment by etj** [comment]
Documentazione su
https://docs.google.com/document/d/1iYwASs_MbuLAmhsfEvuuh1yp0Q9NUZD3h0vM8Cdy8WI/edit?pli=1#heading=h.ya0eu5iagea
