### ISSUE TITLE
Facet Organizzazione

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#47]
Aggiunta di facets di ricerca per gruppi (PA) utilizzando gli IPA degli enti coinvolti nel catalogo.

**Comment by taba90** [comment]
bloccata da https://github.com/geosolutions-it/iso19139.rndt/issues/130

**Comment by taba90** [comment]
per aggiungere facet è necessario editare a mano il file config-summary xml. Nel caso specifico:
- creare due elementi facet dentro l'elemento l'elemento facets uno per l'iPA e uno per la PA
`<facet name="pubblicaAmministrazione" indexKey="pa" label="pubblicaAmministrazione"/>`    
`<facet name="iPA" indexKey="ipa" label="iPA"/>`

- Aggiungere un elemento item per ciascuna facet dentro gli elementi summaryTypes di interesse:
`<item facet="pubblicaAmministrazione"/>`
`<item facet="iPA"/>`
- Se geonetwork è già stato deployato eliminare la folder index

**Comment by taba90** [comment]
[config-summary.zip](https://github.com/geosolutions-it/core-geonetwork/files/5502042/config-summary.zip)
config-summary.xml con le facet definite per iPA e PA ed aggiunte ad ogni summaryType disponibile.

**Comment by etj** [comment]
@etj Controllare se il file  `config-summary.xml` può riesedere nella data directory esternalizzata

**Comment by etj** [comment]
Il file `config-summary.xml` NON viene gestito nella data directory esternalizzata
```
gn/310x/core-geonetwork$ find -name config-summary.xml

./web/target/geonetwork/WEB-INF/config-summary.xml
./web/src/main/webapp/WEB-INF/config-summary.xml
```

**Comment by etj** [comment]
Il file `config-summary.xml` è riferito all'interno di  `web/src/main/webapp/WEB-INF/config.xml`, che dovrebbe essere un vecchio formato di configurazione di jeeves, e come `import` in un file spring `web/src/main/webResources/WEB-INF/config-spring-geonetwork.xml`.
Non mi sembra sia possibile farne override tramite spring.

**Comment by tdipisa** [comment]
@etj dal momento che si tratta di una questione di configurazione/deploy specifica direi di inserire tutto (questo e altro necessario in futuro) in un repository dedicato al cliente aggiornando di conseguenza la documentazione e i necessari steps di configurazione/deploy. @etj ho creato un repository dedicato [qui](https://github.com/geosolutions-it/C024-CMF)

**Comment by taba90** [comment]
pr con il file di configurazione nel repository dedicato https://github.com/geosolutions-it/C024-CMF/pull/2
