### ISSUE TITLE
Logo Organizzazione

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#48]
Ogni metadato deve essere identificato dal logo della PA (sia nella scheda di dettaglio del metadato che nella lista dei risultati di ricerca)

**Comment by taba90** [comment]
Funziona per la schermata di ricerca e per la scheda di dettaglio:

![Logo2](https://user-images.githubusercontent.com/46672505/98262849-607fd080-1f86-11eb-8048-d8911e639c02.PNG)


![logo1](https://user-images.githubusercontent.com/46672505/98262861-65448480-1f86-11eb-8553-0904ace18f1c.PNG)

**Comment by tdipisa** [comment]
La documentazione sull'impostazione del logo qui:
https://docs.google.com/document/d/1iYwASs_MbuLAmhsfEvuuh1yp0Q9NUZD3h0vM8Cdy8WI/edit#heading=h.9365fxvum8gv

**Comment by tdipisa** [comment]
@taba90 @etj Stavo notando che il logo dell'organizzazione impostato precedentemente non è più visibile sui metadati. Potete fare un controllo?
