### ISSUE TITLE
Interoperabilità cataloghi Evoluzione infrastruttura ODN

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/core-geonetwork#50]
Tasks specifici ODN.

**Comment by simboss** [comment]
@tdipisa what the status on this one? Can you update it as well as its issues?

**Comment by tdipisa** [comment]
@simboss this is the epic that involves also the installation for Linea comune (https://github.com/geosolutions-it/core-geonetwork/issues/42). It is the only one in backlog, the status is already updated as reported in the above epic list.
