### ISSUE TITLE
Tomcat user should be able to write in schema_plugins/iso19139.rndt/

### ISSUE THREAD

**Issue by conjame** [geosolutions-it/core-geonetwork#56]
Tomcat user should be able to write to /var/lib/tomcat/geonetwork/gn/data/config/schema_plugins/iso19139.rndt/ , current directory owner is 'jenkins'.

[doc](https://docs.google.com/document/d/1Luzu1MTpazc8TkBd106W13KZXIQCD4k-hcWeiIRc6sQ/edit#heading=h.oh6l2cj3i54b)

[jenkins deploy job](https://build.geo-solutions.it/jenkins/job/Deploy%20GeoNetwork-RNDT-3.10.x-rndt3/)

**Comment by randomorder** [comment]
`tomcat` user belongs to the `jenkins` group. Should be just a matter of granting write permissions to the group, no @giacomoc92 ?
`chmod g+w  /var/lib/tomcat/geonetwork/gn/data/config/schema_plugins/iso19139.rndt/ -R` ?

**Comment by conjame** [comment]
> tomcat user belongs to the jenkins group. Should be just a matter of granting write permissions to the group, no @giacomoc92 ?

![image](https://user-images.githubusercontent.com/49372260/98532478-0a5ea600-2282-11eb-9005-ac0e201a8617.png)

yes

![image](https://user-images.githubusercontent.com/49372260/98532836-835dfd80-2282-11eb-96d4-609cd2a345b0.png)

@etj should be fixed now

**Comment by tdipisa** [comment]
@etj any update from you about this?

**Comment by etj** [comment]
Uhm, error is more general that this. schematron files are "compiled" into "xsl" files for all the schemas, so write acces is needed for all the schemas.

**Comment by etj** [comment]
Issued a 

    chmod g+w /var/lib/tomcat/geonetwork/gn/data/config/schema_plugins/ -R

restarted geonetwork and now it works like a charme!

**Comment by tdipisa** [comment]
@etj  can we close this then?

**Comment by etj** [comment]
Since the rndt directory is uploaded as part of the deploy, pls make sure the group permissions are kept.

**Comment by randomorder** [comment]
@giacomoc92 ?

**Comment by conjame** [comment]
> Issued a
> 
> ```
> chmod g+w /var/lib/tomcat/geonetwork/gn/data/config/schema_plugins/ -R
> ```
> 
> restarted geonetwork and now it works like a charme!

I have updated the deploy job so the group permissions are reapplied after the upload @randomorder 

![image](https://user-images.githubusercontent.com/49372260/99420397-733ac380-28fd-11eb-874e-e0b0de422f80.png)

![image](https://user-images.githubusercontent.com/49372260/99420560-a1b89e80-28fd-11eb-971d-047a555f8576.png)

can we close this ?
