### ISSUE TITLE
CSW harvester: opt to swap detectSchema and XSL processing

### ISSUE THREAD

**Issue by etj** [geosolutions-it/core-geonetwork#58]
The CSW Aligner performs, in this order:
- schema detection
- record filtering by xpath
- xsl transformation
- batch editing

It may be useful to perform a transformation of the harvested metadata before the schema detection.

Transformations are performed both via xsl, and via batch editing. The batch editing anyway needs a namespace declaration, which is provided by the detected schema. This leaves the xsl as the only available way to perform the transformation.

Please only note that also the xpath filtering needs the schema information.
This means that the 4 processing steps can not be moved around a lot.

We'll add a boolean value that will switch the processing order; 
The default value will leave the order as it is now  (e.g. `performXslBeforeSchemadetect = false`)
When the swapping is requested, the processing order will become:

- xsl transformation (moved as first step)
- schema detection
- record filtering by xpath
- batch editing

(Note that the id extraction after the xsl processing will be anyway performed after the schema detection, since the uuid extractin procedure is schema dependent)

**Comment by taba90** [comment]
pr C024 https://github.com/geosolutions-it/C024-CMF/pull/7

**Comment by tdipisa** [comment]
PR here:
https://github.com/geosolutions-it/core-geonetwork/pull/61
