### ISSUE TITLE
Add rndt geonetwork to https://build.geo-solutions.it/geonetwork/

### ISSUE THREAD

**Issue by conjame** [geosolutions-it/core-geonetwork#67]
We want to store at https://build.geo-solutions.it/geonetwork/rndt/ the result of the [jenkins build](https://build.geo-solutions.it/jenkins/view/GeoNetwork/job/Build_GeoNetwork-RNDT-3.10.x-rndt3/) (geonetwork.war complete with the additional jars) and schema-iso19139.rndt.jar

**Comment by tdipisa** [comment]
@giacomoc92 any news for this?

**Comment by conjame** [comment]
Got blocked for a while as the build server became extremely slow and unresponsive. 
Anyways [the job](https://build.geo-solutions.it/jenkins/job/Build_GeoNetwork-RNDT-3.10.x-rndt3/) is updated and the files are here https://build.geo-solutions.it/geonetwork/RNDT/3.10.x/

moving to review @etj @tdipisa

**Comment by randomorder** [comment]
who should review this @giacomoc92 @tdipisa ?

**Comment by tdipisa** [comment]
@etj can you please do a quick check and confirm that we can close the issue?

**Comment by etj** [comment]
@tdipisa files are properly deployed, seems fine.

**Comment by tdipisa** [comment]
@randomorder we can close this.
